BEGIN TRANSACTION;

-- BEGINORGANISATIE incorrect
UPDATE "WEGOBJECTEN" 
SET BEGINORGANISATIE = 1
WHERE AARDWEGOBJECT = 5 AND NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "SUBADRESSEN" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "SUBADRESSEN" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "huisnummers" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "subadresstatussen" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "STRAATKANTEN"
SET BEGINORGANISATIE = 1
WHERE 
NOT (STRAATKANTEN.BEGINORGANISATIE = 1 OR STRAATKANTEN.BEGINORGANISATIE = 99)
AND EXISTS
  (SELECT ID FROM WEGOBJECTEN
   WHERE STRAATKANTEN.WEGOBJECTID = WEGOBJECTEN.ID
   AND WEGOBJECTEN.AARDWEGOBJECT = 5  );
  
UPDATE "POSTKANTONCODES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "huisnummerstatussen"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_RRADRES_RELATIES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_RRADRES_RELATIES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_KADADRES_RELATIES"
SET BEGINORGANISATIE = 5
WHERE  NOT( BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

-- geldigheidsperiode -> dubbels: verwijder alle dubbels behalve jongste record, einddatum is begindatum jongste record, eindtijd is huidige tijd
UPDATE ADRES_RRADRES_RELATIES 
SET EINDDATUM =  (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM ADRES_RRADRES_RELATIES t2 
        WHERE t2.ID <> ADRES_RRADRES_RELATIES.ID 
        AND t2.rradresid = ADRES_RRADRES_RELATIES.rradresid
        AND t2.adresid = ADRES_RRADRES_RELATIES.adresid
        AND t2.aardadres = ADRES_RRADRES_RELATIES.aardadres
    )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM ADRES_RRADRES_RELATIES t3 
        WHERE t3.ID <> ADRES_RRADRES_RELATIES.ID 
        AND t3.rradresid = ADRES_RRADRES_RELATIES.rradresid
        AND t3.adresid = ADRES_RRADRES_RELATIES.adresid
        AND t3.aardadres = ADRES_RRADRES_RELATIES.aardadres
    AND t3.begindatum > ADRES_RRADRES_RELATIES.begindatum
    );
    
UPDATE RRSTRAATNAAM_STRAATNAAM_RELATIES 
SET EINDDATUM = ( 
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM RRSTRAATNAAM_STRAATNAAM_RELATIES t2 
        WHERE t2.ID <> RRSTRAATNAAM_STRAATNAAM_RELATIES.ID 
        AND t2.RRSTRAATCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.RRSTRAATCODE
        AND t2.SUBKANTONCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.SUBKANTONCODE
    )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM RRSTRAATNAAM_STRAATNAAM_RELATIES t3 
        WHERE t3.ID <> RRSTRAATNAAM_STRAATNAAM_RELATIES.ID 
        AND t3.RRSTRAATCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.RRSTRAATCODE
        AND t3.SUBKANTONCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.SUBKANTONCODE
    AND t3.begindatum > RRSTRAATNAAM_STRAATNAAM_RELATIES.begindatum
    ); 
    
UPDATE POSTKANTONCODES 
SET EINDDATUM = (
    SELECT  MIN(DATE(t2.begindatum, '-1 day' )) FROM POSTKANTONCODES t2 
        WHERE t2.ID <> POSTKANTONCODES.ID 
        AND   t2.huisnummerid = POSTKANTONCODES.huisnummerid  
    )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM POSTKANTONCODES t3
        WHERE t3.ID <> POSTKANTONCODES.ID 
        AND   t3.huisnummerid = POSTKANTONCODES.huisnummerid
    AND t3.begindatum > POSTKANTONCODES.begindatum
    );  
    
UPDATE HUISNUMMERS 
SET EINDDATUM = (  
    SELECT MIN(DATE(t2.begindatum, '-1 day' ))  FROM  HUISNUMMERS t2 
        WHERE HUISNUMMERS.id <> t2.id 
        AND HUISNUMMERS.straatnaamid = t2.straatnaamid  
        AND HUISNUMMERS.huisnummer = t2.huisnummer
    )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM  HUISNUMMERS t3 
        WHERE HUISNUMMERS.id <> t3.id 
        AND HUISNUMMERS.straatnaamid = t3.straatnaamid  
        AND HUISNUMMERS.huisnummer = t3.huisnummer
    AND t3.begindatum > HUISNUMMERS.begindatum
    );
   
UPDATE HUISNUMMERSTATUSSEN  
SET EINDDATUM = (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM  HUISNUMMERSTATUSSEN  t2 
        WHERE HUISNUMMERSTATUSSEN.id <> t2.id 
        AND HUISNUMMERSTATUSSEN.huisnummerid = t2.huisnummerid
        )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM  HUISNUMMERSTATUSSEN  t3 
        WHERE HUISNUMMERSTATUSSEN.id <> t3.id 
        AND HUISNUMMERSTATUSSEN.huisnummerid = t3.huisnummerid
    AND t3.begindatum > HUISNUMMERSTATUSSEN.begindatum
    );
   
UPDATE SUBADRESSEN     
SET EINDDATUM =  (     
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM SUBADRESSEN t2 
        WHERE SUBADRESSEN.ID <> t2.ID 
        AND SUBADRESSEN.huisnummerid = t2.huisnummerid
        AND SUBADRESSEN.subadres = t2.subadres
        AND SUBADRESSEN.aardsubadres = t2.aardsubadres 
        )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM SUBADRESSEN t3 
        WHERE SUBADRESSEN.ID <> t3.ID 
        AND SUBADRESSEN.huisnummerid = t3.huisnummerid
        AND SUBADRESSEN.subadres = t3.subadres
        AND SUBADRESSEN.aardsubadres = t3.aardsubadres
    AND t3.begindatum > SUBADRESSEN.begindatum
    );

UPDATE SUBADRESSTATUSSEN
SET EINDDATUM =  (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM SUBADRESSTATUSSEN t2 
        WHERE SUBADRESSTATUSSEN.ID <> t2.ID 
        AND SUBADRESSTATUSSEN.subadresid = t2.subadresid 
        )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM SUBADRESSTATUSSEN t3 
        WHERE SUBADRESSTATUSSEN.ID <> t3.ID 
        AND SUBADRESSTATUSSEN.subadresid = t3.subadresid
    AND t3.begindatum > SUBADRESSTATUSSEN.begindatum
    );
    
UPDATE STRAATNAAMSTATUSSEN     
SET EINDDATUM = (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM STRAATNAAMSTATUSSEN t2 
        WHERE STRAATNAAMSTATUSSEN.ID <> t2.ID 
        AND STRAATNAAMSTATUSSEN.straatnaamid = t2.straatnaamid
) 
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM STRAATNAAMSTATUSSEN t3 
        WHERE STRAATNAAMSTATUSSEN.ID <> t3.ID 
        AND STRAATNAAMSTATUSSEN.straatnaamid = t3.straatnaamid
    AND t3.begindatum > STRAATNAAMSTATUSSEN.begindatum
    );
   
UPDATE TERREINOBJECT_HUISNUMMER_RELATIES     
SET EINDDATUM = (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM TERREINOBJECT_HUISNUMMER_RELATIES t2 
        WHERE TERREINOBJECT_HUISNUMMER_RELATIES.ID <> t2.ID 
        AND TERREINOBJECT_HUISNUMMER_RELATIES.terreinobjectid = t2.terreinobjectid
        AND TERREINOBJECT_HUISNUMMER_RELATIES.huisnummerid = t2.huisnummerid
        )  
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t3 
        WHERE TERREINOBJECT_HUISNUMMER_RELATIES.ID <> t3.ID 
        AND TERREINOBJECT_HUISNUMMER_RELATIES.terreinobjectid = t3.terreinobjectid
        AND TERREINOBJECT_HUISNUMMER_RELATIES.huisnummerid = t3.huisnummerid
    AND t3.begindatum > TERREINOBJECT_HUISNUMMER_RELATIES.begindatum
    );
   
UPDATE WEGVERBINDINGGEOMETRIEN      
SET EINDDATUM =  (
    SELECT MIN(DATE(t2.begindatum, '-1 day' )) FROM WEGVERBINDINGGEOMETRIEN  t2 
        WHERE WEGVERBINDINGGEOMETRIEN.ID <> t2.ID 
        AND WEGVERBINDINGGEOMETRIEN.wegobjectid = t2.wegobjectid 
        )
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM WEGVERBINDINGGEOMETRIEN  t3 
        WHERE WEGVERBINDINGGEOMETRIEN.ID <> t3.ID 
        AND WEGVERBINDINGGEOMETRIEN.wegobjectid = t3.wegobjectid
    AND t3.begindatum > WEGVERBINDINGGEOMETRIEN.begindatum
    );   
    
UPDATE ADRESPOSITIES 
SET EINDDATUM =  (
        SELECT MIN(DATE(t2.begindatum, '-1 day' ))FROM ADRESPOSITIES t2
        WHERE ADRESPOSITIES.id <> t2.id 
        AND ADRESPOSITIES.herkomstadrespositie = t2.herkomstadrespositie
        AND ADRESPOSITIES.adresid = t2.adresid
        AND ADRESPOSITIES.aardadres = t2.aardadres
)  --date( begindatum,'+1 day'), EINDORGANISATIE = 1 , EINDTIJD =  strftime('%s','now')
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM ADRESPOSITIES t3
        WHERE ADRESPOSITIES.id <> t3.id 
        AND ADRESPOSITIES.herkomstadrespositie = t3.herkomstadrespositie
        AND ADRESPOSITIES.adresid = t3.adresid
        AND ADRESPOSITIES.aardadres = t3.aardadres
    AND t3.begindatum > ADRESPOSITIES.begindatum
    );

--koppeling adresposities op terreinobjecten  komt niet overeen
UPDATE ADRESPOSITIES 
SET  herkomstadrespositie= '10' 
WHERE EINDDATUM IS NULL
AND ADRESPOSITIES.aardadres = '1' 
AND ADRESPOSITIES.herkomstadrespositie IN ('3', '7') 
AND ADRESPOSITIES.adresid IN (
    SELECT t2.SUBADRESID FROM SUBADRESSTATUSSEN t2
    INNER JOIN SUBADRESSEN t5 ON t2.SUBADRESID = t5.ID
    WHERE t2.subadresstatus = '3' 
    AND NOT EXISTS(
      SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t3 
      INNER JOIN TERREINOBJECTEN t4 ON t3.terreinobjectid = t4.ID 
      WHERE t3.huisnummerid = t5.huisnummerid 
      AND t4.aardterreinobject IN ('2','5')
	)
 );

UPDATE ADRESPOSITIES 
SET herkomstadrespositie = '12' 
WHERE EINDDATUM IS NULL 
AND ADRESPOSITIES.aardadres = '1' 
AND ADRESPOSITIES.herkomstadrespositie = '2' 
AND ADRESPOSITIES.adresid IN (
    SELECT t2.SUBADRESID FROM SUBADRESSTATUSSEN t2
    INNER JOIN SUBADRESSEN t5 ON t2.SUBADRESID = t5.ID
    WHERE t2.subadresstatus = '3' 
    AND NOT EXISTS(
      SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t3 
      INNER JOIN TERREINOBJECTEN t4 ON t3.terreinobjectid = t4.ID 
      WHERE t3.huisnummerid = t5.huisnummerid 
      AND t4.aardterreinobject IN ('1','4')
	)
 );
 
--temporele integriteit -> stel einddatum voor records waarvan de gerelateerde records een einddatum hebben gekregen.
UPDATE HUISNUMMERSTATUSSEN
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = HUISNUMMERSTATUSSEN.huisnummerid )
WHERE eindtijd IS NULL AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = HUISNUMMERSTATUSSEN.huisnummerid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(HUISNUMMERSTATUSSEN.einddatum, '9999-01-01')
        );    
  
UPDATE SUBADRESSEN
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = SUBADRESSEN.huisnummerid )
WHERE eindtijd IS NULL AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = SUBADRESSEN.huisnummerid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(SUBADRESSEN.einddatum, '9999-01-01')
        );   

UPDATE ADRES_KADADRES_RELATIES
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = ADRES_KADADRES_RELATIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '2'  
AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = ADRES_KADADRES_RELATIES.adresid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(ADRES_KADADRES_RELATIES.einddatum, '9999-01-01')
        );   
      
UPDATE ADRES_KADADRES_RELATIES
SET einddatum = (
        SELECT SUBADRESSEN.einddatum 
        FROM SUBADRESSEN WHERE SUBADRESSEN.ID = ADRES_KADADRES_RELATIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '1' 
AND EXISTS (
        SELECT NULL FROM SUBADRESSEN 
        WHERE SUBADRESSEN.eindtijd IS NULL AND SUBADRESSEN.ID = ADRES_KADADRES_RELATIES.adresid 
        AND IFNULL(SUBADRESSEN.einddatum, '9999-01-01') < IFNULL(ADRES_KADADRES_RELATIES.einddatum, '9999-01-01')
        );   

UPDATE TERREINOBJECT_HUISNUMMER_RELATIES
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = TERREINOBJECT_HUISNUMMER_RELATIES.huisnummerid )
WHERE eindtijd IS NULL
AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = TERREINOBJECT_HUISNUMMER_RELATIES.huisnummerid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(TERREINOBJECT_HUISNUMMER_RELATIES.einddatum, '9999-01-01')
        );   

UPDATE SUBADRESSTATUSSEN
SET einddatum = (
        SELECT SUBADRESSEN.einddatum 
        FROM SUBADRESSEN WHERE SUBADRESSEN.ID = SUBADRESSTATUSSEN.SUBADRESID )
WHERE eindtijd IS NULL 
AND EXISTS (
        SELECT NULL FROM SUBADRESSEN 
        WHERE SUBADRESSEN.eindtijd IS NULL AND SUBADRESSEN.ID = SUBADRESSTATUSSEN.SUBADRESID 
        AND IFNULL(SUBADRESSEN.einddatum, '9999-01-01') < IFNULL(SUBADRESSTATUSSEN.einddatum, '9999-01-01')
        );   
 
UPDATE POSTKANTONCODES
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = POSTKANTONCODES.huisnummerid )
WHERE eindtijd IS NULL 
AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = POSTKANTONCODES.huisnummerid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(POSTKANTONCODES.einddatum, '9999-01-01')
        );   
 
UPDATE ADRES_RRADRES_RELATIES
SET einddatum = (
        SELECT SUBADRESSEN.einddatum 
        FROM SUBADRESSEN WHERE SUBADRESSEN.ID = ADRES_RRADRES_RELATIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '1'  
AND EXISTS (
        SELECT NULL FROM SUBADRESSEN 
        WHERE SUBADRESSEN.eindtijd IS NULL AND SUBADRESSEN.ID = ADRES_RRADRES_RELATIES.adresid 
        AND IFNULL(SUBADRESSEN.einddatum, '9999-01-01') < IFNULL(ADRES_RRADRES_RELATIES.einddatum, '9999-01-01')
        );   
        
UPDATE ADRES_RRADRES_RELATIES
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = ADRES_RRADRES_RELATIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '2'  
AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = ADRES_RRADRES_RELATIES.adresid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(ADRES_RRADRES_RELATIES.einddatum, '9999-01-01')
        );   

UPDATE ADRESPOSITIES
SET einddatum = (
        SELECT HUISNUMMERS.einddatum 
        FROM HUISNUMMERS WHERE HUISNUMMERS.ID = ADRESPOSITIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '2'  
AND EXISTS (
        SELECT NULL FROM HUISNUMMERS 
        WHERE HUISNUMMERS.eindtijd IS NULL AND HUISNUMMERS.ID = ADRESPOSITIES.adresid 
        AND IFNULL(HUISNUMMERS.einddatum, '9999-01-01') < IFNULL(ADRESPOSITIES.einddatum, '9999-01-01')
        );  

UPDATE ADRESPOSITIES
SET einddatum = (
        SELECT SUBADRESSEN.einddatum 
        FROM SUBADRESSEN WHERE SUBADRESSEN.ID = ADRESPOSITIES.adresid )
WHERE eindtijd IS NULL AND aardadres = '1'  
AND EXISTS (
        SELECT NULL FROM SUBADRESSEN 
        WHERE SUBADRESSEN.eindtijd IS NULL AND SUBADRESSEN.ID = ADRESPOSITIES.adresid 
        AND IFNULL(SUBADRESSEN.einddatum, '9999-01-01') < IFNULL(ADRESPOSITIES.einddatum, '9999-01-01')
        );  

-- eind/begin organisatie ADRESPOSITIE komt niet overeen met de herkomstadrespositie
UPDATE "adresposities"
SET BEGINORGANISATIE = 5
WHERE  herkomstadrespositie IN ('10', '11', '12', '13', '14', '15', '16', '17', '18') 
 AND NOT( BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE ADRESPOSITIES
SET eindorganisatie = '5'
WHERE  herkomstadrespositie IN ('10', '11', '12', '13', '14', '15', '16', '17', '18') 
    AND eindorganisatie IS NOT NULL 
    AND eindorganisatie NOT IN ('5', '99');

COMMIT;

