BEGIN TRANSACTION;

-- BEGINORGANISATIE incorrect
UPDATE "WEGOBJECTEN" 
SET BEGINORGANISATIE = 1
WHERE AARDWEGOBJECT = 5 AND NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "SUBADRESSEN" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "SUBADRESSEN" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR BEGINORGANISATIE= 99) ;

UPDATE "huisnummers" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "subadresstatussen" 
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "STRAATKANTEN"
SET BEGINORGANISATIE = 1
WHERE 
NOT (STRAATKANTEN.BEGINORGANISATIE = 1 OR STRAATKANTEN.BEGINORGANISATIE = 99)
AND EXISTS
  (SELECT ID FROM WEGOBJECTEN
   WHERE STRAATKANTEN.WEGOBJECTID = WEGOBJECTEN.ID
   AND WEGOBJECTEN.AARDWEGOBJECT = 5  );
  
UPDATE "POSTKANTONCODES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "huisnummerstatussen"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "adresposities"
SET BEGINORGANISATIE = 5
WHERE  herkomstadrespositie IN ('10', '11', '12', '13', '14', '15', '16', '17', '18') 
 AND NOT( BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_RRADRES_RELATIES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_RRADRES_RELATIES"
SET BEGINORGANISATIE = 1
WHERE  NOT( BEGINORGANISATIE= 1 OR  BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

UPDATE "ADRES_KADADRES_RELATIES"
SET BEGINORGANISATIE = 5
WHERE  NOT( BEGINORGANISATIE= 5 OR BEGINORGANISATIE= 99) ;

-- geldigheid periode -> dubbels verwijder alle dubbels behalve oudste
UPDATE ADRES_RRADRES_RELATIES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now') , EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM ADRES_RRADRES_RELATIES t2 
        WHERE t2.ID <> ADRES_RRADRES_RELATIES.ID 
        AND t2.rradresid = ADRES_RRADRES_RELATIES.rradresid
        AND t2.adresid = ADRES_RRADRES_RELATIES.adresid
        AND t2.aardadres = ADRES_RRADRES_RELATIES.aardadres
    AND t2.begindatum > ADRES_RRADRES_RELATIES.begindatum
    );
    
UPDATE RRSTRAATNAAM_STRAATNAAM_RELATIES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now') , EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM RRSTRAATNAAM_STRAATNAAM_RELATIES t2 
        WHERE t2.ID <> RRSTRAATNAAM_STRAATNAAM_RELATIES.ID 
        AND t2.RRSTRAATCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.RRSTRAATCODE
        AND t2.SUBKANTONCODE = RRSTRAATNAAM_STRAATNAAM_RELATIES.SUBKANTONCODE
    AND t2.begindatum > RRSTRAATNAAM_STRAATNAAM_RELATIES.begindatum
    ); 
    
UPDATE POSTKANTONCODES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now') , EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM POSTKANTONCODES t2 
        WHERE t2.ID <> POSTKANTONCODES.ID 
        AND   t2.huisnummerid = POSTKANTONCODES.huisnummerid
    AND t2.begindatum > POSTKANTONCODES.begindatum
    );  
    
UPDATE HUISNUMMERS 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now') , EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM  HUISNUMMERS t2 
        WHERE HUISNUMMERS.id <> t2.id 
        AND HUISNUMMERS.straatnaamid = t2.straatnaamid  
        AND HUISNUMMERS.huisnummer = t2.huisnummer
    AND t2.begindatum > HUISNUMMERS.begindatum
    );
   
UPDATE HUISNUMMERSTATUSSEN  
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now') , EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM  HUISNUMMERSTATUSSEN  t2 
        WHERE HUISNUMMERSTATUSSEN.id <> t2.id 
        AND HUISNUMMERSTATUSSEN.huisnummerid = t2.huisnummerid
    AND t2.begindatum > HUISNUMMERSTATUSSEN.begindatum
    );
   
UPDATE SUBADRESSEN     
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM SUBADRESSEN t2 
        WHERE SUBADRESSEN.ID <> t2.ID 
        AND SUBADRESSEN.huisnummerid = t2.huisnummerid
        AND SUBADRESSEN.subadres = t2.subadres
        AND SUBADRESSEN.aardsubadres = t2.aardsubadres
    AND t2.begindatum > SUBADRESSEN.begindatum
    );

UPDATE SUBADRESSTATUSSEN
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM SUBADRESSTATUSSEN t2 
        WHERE SUBADRESSTATUSSEN.ID <> t2.ID 
        AND SUBADRESSTATUSSEN.subadresid = t2.subadresid
    AND t2.begindatum > SUBADRESSTATUSSEN.begindatum
    );
    
UPDATE STRAATNAAMSTATUSSEN     
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM STRAATNAAMSTATUSSEN t2 
        WHERE STRAATNAAMSTATUSSEN.ID <> t2.ID 
        AND STRAATNAAMSTATUSSEN.straatnaamid = t2.straatnaamid
    AND t2.begindatum > STRAATNAAMSTATUSSEN.begindatum
    );
   
UPDATE TERREINOBJECT_HUISNUMMER_RELATIES     
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t2 
        WHERE TERREINOBJECT_HUISNUMMER_RELATIES.ID <> t2.ID 
        AND TERREINOBJECT_HUISNUMMER_RELATIES.terreinobjectid = t2.terreinobjectid
        AND TERREINOBJECT_HUISNUMMER_RELATIES.huisnummerid = t2.huisnummerid
    AND t2.begindatum > TERREINOBJECT_HUISNUMMER_RELATIES.begindatum
    );
   
UPDATE WEGVERBINDINGGEOMETRIEN      
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM WEGVERBINDINGGEOMETRIEN  t2 
        WHERE WEGVERBINDINGGEOMETRIEN.ID <> t2.ID 
        AND WEGVERBINDINGGEOMETRIEN.wegobjectid = t2.wegobjectid
    AND t2.begindatum > WEGVERBINDINGGEOMETRIEN.begindatum
    );   
    
UPDATE ADRESPOSITIES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL AND EXISTS(
    SELECT NULL FROM ADRESPOSITIES t2
        WHERE ADRESPOSITIES.id <> t2.id 
        AND ADRESPOSITIES.herkomstadrespositie = t2.herkomstadrespositie
        AND ADRESPOSITIES.adresid = t2.adresid
        AND ADRESPOSITIES.aardadres = t2.aardadres
    AND t2.begindatum > ADRESPOSITIES.begindatum
    );

UPDATE ADRESPOSITIES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL 
AND ADRESPOSITIES.aardadres = '1' 
AND ADRESPOSITIES.herkomstadrespositie = '2' 
AND ADRESPOSITIES.adresid IN (
    SELECT t2.SUBADRESID FROM SUBADRESSTATUSSEN t2
    INNER JOIN SUBADRESSEN t5 ON t2.SUBADRESID = t5.ID
    WHERE t2.subadresstatus = '3' 
    AND NOT EXISTS(
      SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t3 
      INNER JOIN TERREINOBJECTEN t4 ON t3.terreinobjectid = t4.ID 
      WHERE t3.huisnummerid = t5.huisnummerid 
      AND t4.aardterreinobject IN ('1','4')
	)
 );
 
UPDATE ADRESPOSITIES 
SET EINDDATUM =  date( begindatum,'+1 day'), EINDTIJD =  strftime('%s','now'), EINDORGANISATIE = 1
WHERE EINDDATUM IS NULL 
AND ADRESPOSITIES.aardadres = '1' 
AND ADRESPOSITIES.herkomstadrespositie IN ('3', '7') 
AND ADRESPOSITIES.adresid IN (
    SELECT t2.SUBADRESID FROM SUBADRESSTATUSSEN t2
    INNER JOIN SUBADRESSEN t5 ON t2.SUBADRESID = t5.ID
    WHERE t2.subadresstatus = '3' 
    AND NOT EXISTS(
      SELECT NULL FROM TERREINOBJECT_HUISNUMMER_RELATIES t3 
      INNER JOIN TERREINOBJECTEN t4 ON t3.terreinobjectid = t4.ID 
      WHERE t3.huisnummerid = t5.huisnummerid 
      AND t4.aardterreinobject IN ('2','5')
	)
 );

--changes in eindorganisatie afther everything else.
UPDATE ADRESPOSITIES
SET eindorganisatie = 5
WHERE  herkomstadrespositie IN ('10', '11', '12', '13', '14', '15', '16', '17', '18') 
    AND eindorganisatie IS NOT NULL 
    AND eindorganisatie NOT IN ('5', '99');

COMMIT;

