BEGIN TRANSACTION;
CREATE VIEW geenTerreinKoppeling AS
SELECT  ap.SHAPE AS shape, ap.ID as ADRESID, h.ID AS HUISNUMMERID,
        ap.X AS X, ap.Y AS Y, ap.HERKOMSTADRESPOSITIE AS HERKOMSTADRESPOSITIE,
        HERKOMSTADRESPOSITIES.BESCHRIJVING AS HERKOMST, 'ANTWERPEN' AS GEMEENTE, 
        h.HUISNUMMER AS HUISNUMMER, s.STRAATNAAM AS STRAATNAAM, 
        s.STRAATCODE AS STRAATCODE, s.ID AS STRAAT_CRABCODE, 
        POSTKANTONCODES.POSTKANTONCODE AS POSTCODE,  
        TERREINOBJECTEN.IDENTIFICATORTERREINOBJECT AS PERCEEL_OF_GEBOUW
        
FROM  HUISNUMMERS h
        INNER JOIN STRAATNAMEN s ON h.STRAATNAAMID = s.ID
        INNER JOIN ADRESPOSITIES ap ON h.ID = ap.ADRESID AND ap.AARDADRES = '2'
        INNER JOIN HUISNUMMERSTATUSSEN hs ON h.ID = hs.HUISNUMMERID
        
        LEFT JOIN HERKOMSTADRESPOSITIES
	        ON ap.HERKOMSTADRESPOSITIE = HERKOMSTADRESPOSITIES.ID
        LEFT JOIN POSTKANTONCODES
            ON h.ID = POSTKANTONCODES.HUISNUMMERID
        LEFT JOIN TERREINOBJECT_HUISNUMMER_RELATIES th1
            ON  ap.ADRESID = th1.HUISNUMMERID
        LEFT JOIN TERREINOBJECTEN
            ON th1.TERREINOBJECTID = TERREINOBJECTEN.ID 
    
WHERE   h.einddatum IS NULL
        AND hs.einddatum IS NULL
        AND hs.huisnummerstatus = '3'
        AND ap.einddatum IS NULL
        AND ap.herkomstadrespositie NOT IN ( '8', '9' ) --ligplaats of standplaaats
        AND NOT EXISTS ( SELECT NULL
                         FROM   TERREINOBJECT_HUISNUMMER_RELATIES th
                                INNER JOIN TERREINOBJECTEN t ON th.TERREINOBJECTID = t.ID
                         WHERE  th.HUISNUMMERID = h.ID
                                AND th.einddatum IS NULL
                                AND t.AARDTERREINOBJECT IN ( '1', '5' ) ) ;

--create the spatial view 
INSERT INTO views_geometry_columns
    (view_name, view_geometry, view_rowid, f_table_name, f_geometry_column, read_only)
  VALUES ('geenterreinkoppeling', 'shape', 'rowid', 'adresposities', 'shape', 0);
  
COMMIT;  
-- SELECT 
-- ADRESPOSITIES."SHAPE" AS shape, 
-- ADRESPOSITIES."ID" AS ADRESID,  
-- HUISNUMMERS."ID" AS HUISNUMMERID,
-- ADRESPOSITIES."X" AS X, ADRESPOSITIES."Y" AS Y, 
-- ADRESPOSITIES.HERKOMSTADRESPOSITIE AS HERKOMSTADRESPOSITIE,
-- HERKOMSTADRESPOSITIES."BESCHRIJVING" AS HERKOMST, 
-- HUISNUMMERS."HUISNUMMER" AS HUISNUMMER,
-- STRAATNAMEN."STRAATNAAM" AS STRAATNAAM, 
-- STRAATNAMEN."STRAATCODE" AS STRAATCODE, 
-- STRAATNAMEN."ID" AS STRAAT_CRABCODE, 
-- POSTKANTONCODES."POSTKANTONCODE" AS POSTCODE, 
-- 'ANTWERPEN' AS GEMEENTE,  
-- TERREINOBJECTEN."IDENTIFICATORTERREINOBJECT" AS PERCEEL_OF_GEBOUW

-- FROM "ADRESPOSITIES"
-- INNER JOIN "HUISNUMMERS"
	-- ON ADRESPOSITIES."ADRESID" = HUISNUMMERS."ID"

-- LEFT JOIN "STRAATNAMEN"
	-- ON HUISNUMMERS."STRAATNAAMID" = STRAATNAMEN."ID"

-- LEFT JOIN "POSTKANTONCODES"
	-- ON HUISNUMMERS."ID" = POSTKANTONCODES."HUISNUMMERID"

-- LEFT JOIN "HERKOMSTADRESPOSITIES"
	-- ON ADRESPOSITIES."HERKOMSTADRESPOSITIE" = HERKOMSTADRESPOSITIES."ID"

-- LEFT JOIN "TERREINOBJECT_HUISNUMMER_RELATIES"
    -- ON  ADRESPOSITIES."ADRESID" = TERREINOBJECT_HUISNUMMER_RELATIES."HUISNUMMERID"

-- LEFT JOIN "TERREINOBJECTEN"
    -- ON TERREINOBJECT_HUISNUMMER_RELATIES."TERREINOBJECTID" = TERREINOBJECTEN."ID"

-- WHERE TERREINOBJECT_HUISNUMMER_RELATIES.HUISNUMMERID IS NULL
-- AND ADRESPOSITIES.AARDADRES = '2';

