BEGIN TRANSACTION;
CREATE TABLE "GBKA_JOIN_GEEN_TERREIN" AS
SELECT DISTINCT
geenTerreinKoppeling.ADRESID AS ADRESID,
geenTerreinKoppeling.HUISNUMMERID AS HUISNR_ID,
geenTerreinKoppeling.HUISNUMMER as HUISNR, 
geenTerreinKoppeling.STRAATNAAM as straat, 
geenTerreinKoppeling.POSTCODE as postcode, 
CAST( GBKA_ADRESSEN.CRABCODE AS INTEGER) as CRABCODE, 
GBKA_ADRESSEN.SHAPE as SHAPE
FROM geenTerreinKoppeling
INNER JOIN  GBKA_ADRESSEN
	ON ( CAST( geenTerreinKoppeling.STRAAT_CRABCODE AS INTEGER ) = 
	     CAST( GBKA_ADRESSEN.CRABCODE AS INTEGER )
         AND  HUISNR  = geenTerreinKoppeling.HUISNUMMER 
        )
UNION
SELECT DISTINCT
geenTerreinKoppeling.ADRESID AS ADRESID,
geenTerreinKoppeling.HUISNUMMERID AS HUISNR_ID,
geenTerreinKoppeling.HUISNUMMER as HUISNR, 
geenTerreinKoppeling.STRAATNAAM as straat, 
geenTerreinKoppeling.POSTCODE as postcode, 
CAST( GBKA_ADRESSEN.CRABCODE AS INTEGER) as CRABCODE, 
GBKA_ADRESSEN.SHAPE as SHAPE
FROM geenTerreinKoppeling
INNER JOIN  GBKA_ADRESSEN        
    ON (  CAST( geenTerreinKoppeling.STRAAT_CRABCODE AS INTEGER ) = 
	      CAST( GBKA_ADRESSEN.CRABCODE AS INTEGER )
          AND NOT HUISNR  = geenTerreinKoppeling.HUISNUMMER 
          AND CAST( HUISNR AS INTEGER ) = CAST( geenTerreinKoppeling.HUISNUMMER AS INTEGER )
        ) 
UNION
SELECT DISTINCT
geenTerreinKoppeling.ADRESID AS ADRESID,
geenTerreinKoppeling.HUISNUMMERID AS HUISNR_ID,
CAST( geenTerreinKoppeling.HUISNUMMER AS INTEGER) as HUISNR, 
geenTerreinKoppeling.STRAATNAAM as straat, 
geenTerreinKoppeling.POSTCODE as postcode, 
CAST( WOONEENHEID2015.CRABCODE AS INTEGER) as CRABCODE, 
WOONEENHEID2015.SHAPE as SHAPE
FROM geenTerreinKoppeling
INNER JOIN  WOONEENHEID2015
	ON ( CAST( geenTerreinKoppeling.STRAAT_CRABCODE AS INTEGER ) = 
	     CAST( WOONEENHEID2015.CRABCODE AS INTEGER )
           AND HUISNR = 
           CAST( geenTerreinKoppeling.HUISNUMMER AS INTEGER )
         )
;
--delete duplicates, need only one join
DELETE FROM GBKA_JOIN_GEEN_TERREIN
WHERE ROWID NOT IN
(
   SELECT MIN(ROWID) FROM GBKA_JOIN_GEEN_TERREIN
   GROUP BY HUISNR_ID, ADRESID
);
COMMIT;