SELECT ADRESPOSITIES."ID" AS ADRESID,  HUISNUMMERS."ID" AS HUISNUMMERID,
ADRESPOSITIES."X" AS X, ADRESPOSITIES."Y" AS Y, 
HERKOMSTADRESPOSITIES."BESCHRIJVING" AS HERKOMST, HUISNUMMERS."HUISNUMMER" AS HUISNUMMER,
STRAATNAMEN."STRAATNAAM" AS STRAATNAAM, POSTKANTONCODES."POSTKANTONCODE" AS POSTCODE, 
'ANTWERPEN' AS GEMEENTE,  TERREINOBJECTEN."IDENTIFICATORTERREINOBJECT" AS PERCEEL

FROM "ADRESPOSITIES"
INNER JOIN "HUISNUMMERS"
	ON ADRESPOSITIES."ADRESID" = HUISNUMMERS."ID"

LEFT JOIN "STRAATNAMEN"
	ON HUISNUMMERS."STRAATNAAMID" = STRAATNAMEN."ID"

LEFT JOIN "POSTKANTONCODES"
	ON HUISNUMMERS."ID" = POSTKANTONCODES."HUISNUMMERID"

LEFT JOIN "HERKOMSTADRESPOSITIES"
	ON ADRESPOSITIES."HERKOMSTADRESPOSITIE" = HERKOMSTADRESPOSITIES."ID"

LEFT JOIN "TERREINOBJECT_HUISNUMMER_RELATIES"
    ON  ADRESPOSITIES."ADRESID" = TERREINOBJECT_HUISNUMMER_RELATIES."HUISNUMMERID"

LEFT JOIN "TERREINOBJECTEN"
    ON TERREINOBJECT_HUISNUMMER_RELATIES."TERREINOBJECTID" = TERREINOBJECTEN."ID"

WHERE TERREINOBJECT_HUISNUMMER_RELATIES."HUISNUMMERID" IS NULL