SELECT ADRESPOSITIES."ID", MakePoint(  ADRESPOSITIES."X", ADRESPOSITIES."Y") AS SHAPE, 
HERKOMSTADRESPOSITIES."BESCHRIJVING" AS TYPE, HUISNUMMERS."HUISNUMMER" AS HUISNUMMER,
STRAATNAMEN."STRAATNAAM", POSTKANTONCODES."POSTKANTONCODE" AS PC, 'ANTWERPEN' AS GEMEENTE,
RRSTRAATNAAM_STRAATNAAM_RELATIES."STRAATNAAMID" AS STRAATNAAMID, 
RRSTRAATNAAM_STRAATNAAM_RELATIES."SUBKANTONCODE" AS SUBKANTONCODE, 
RRSTRAATNAAM_STRAATNAAM_RELATIES."RRSTRAATCODE" As RRSTRAATCODE
FROM "ADRESPOSITIES"
INNER JOIN "HUISNUMMERS"
	ON ADRESPOSITIES."ADRESID" = HUISNUMMERS."ID"

LEFT JOIN "STRAATNAMEN"
	ON HUISNUMMERS."STRAATNAAMID" = STRAATNAMEN."ID"

LEFT JOIN "POSTKANTONCODES"
	ON HUISNUMMERS."ID" = POSTKANTONCODES."HUISNUMMERID"

LEFT JOIN "HERKOMSTADRESPOSITIES"
	ON ADRESPOSITIES."HERKOMSTADRESPOSITIE" = HERKOMSTADRESPOSITIES."ID"

LEFT JOIN "RRSTRAATNAAM_STRAATNAAM_RELATIES"
	ON RRSTRAATNAAM_STRAATNAAM_RELATIES."STRAATNAAMID" = "STRAATNAMEN".ID

WHERE PC IS NULL AND HUISNUMMER NOT LIKE "%zn%"