SELECT ADRESPOSITIES."ID", MakePoint(  ADRESPOSITIES."X", ADRESPOSITIES."Y") AS SHAPE, 
HERKOMSTADRESPOSITIES."BESCHRIJVING" AS TYPE, HUISNUMMERS."HUISNUMMER",
STRAATNAMEN."STRAATNAAM", POSTKANTONCODES."POSTKANTONCODE" AS PC, ADRESPOSITIES.AARDADRES AS AARD
FROM "ADRESPOSITIES"
LEFT JOIN "HUISNUMMERS"
    ON ADRESPOSITIES."ADRESID" = HUISNUMMERS."ID"

LEFT JOIN "STRAATNAMEN"
    ON HUISNUMMERS."STRAATNAAMID" = STRAATNAMEN."ID"

LEFT JOIN "POSTKANTONCODES"
    ON HUISNUMMERS."ID" = POSTKANTONCODES."HUISNUMMERID"

LEFT JOIN "HERKOMSTADRESPOSITIES"
    ON ADRESPOSITIES."HERKOMSTADRESPOSITIE" = HERKOMSTADRESPOSITIES."ID"

WHERE ADRESPOSITIES.AARDADRES = 2 

ORDER BY STRAATNAMEN."STRAATNAAM", TYPE