BEGIN TRANSACTION;
 SELECT InitSpatialMetaData();
 SELECT AddGeometryColumn('WEGVERBINDINGGEOMETRIEN','SHAPE',31370, 'LINESTRING' );
 UPDATE WEGVERBINDINGGEOMETRIEN SET "SHAPE"= SetSRID( GeomFromGML( "WEGVERBINDINGGEOMETRIE" ), 31370 );
 SELECT AddGeometryColumn( 'GEBOUWGEOMETRIEN',  'SHAPE', 31370, 'POLYGON' );
 UPDATE GEBOUWGEOMETRIEN SET "SHAPE"= SetSRID( GeomFromGML( "GEBOUWGEOMETRIE" ), 31370 );
 SELECT AddGeometryColumn( 'ADRESPOSITIES', 'SHAPE',31370, 'POINT');
 UPDATE ADRESPOSITIES SET "SHAPE"= MakePoint( "X", "Y", 31370);
 
 CREATE TRIGGER ADRESPOSITIES_UPDATE_XY AFTER UPDATE OF "SHAPE" ON ADRESPOSITIES
  BEGIN
    UPDATE ADRESPOSITIES 
    SET "X"= X( "SHAPE" ), Y= "Y"( "SHAPE" )
    WHERE ID = old.ID;
  END;
  CREATE TRIGGER ADRESPOSITIES_UPDATE_XSHAPE AFTER UPDATE OF "X" ON ADRESPOSITIES
  BEGIN
    UPDATE ADRESPOSITIES 
    SET SHAPE = MakePoint( "X", "Y", 31370)
    WHERE ID = old.ID;
  END;
  CREATE TRIGGER ADRESPOSITIES_UPDATE_YSHAPE AFTER UPDATE OF "Y" ON ADRESPOSITIES
  BEGIN
    UPDATE ADRESPOSITIES 
    SET SHAPE = MakePoint( "X", "Y", 31370)
    WHERE ID = old.ID;
  END;
  CREATE TRIGGER WEGVERBINDINGGEOMETRIEN_UPDATE_GEOM AFTER UPDATE OF "SHAPE" ON WEGVERBINDINGGEOMETRIEN
  BEGIN
    UPDATE WEGVERBINDINGGEOMETRIEN 
    SET "WEGVERBINDINGGEOMETRIE" = AsGml( "SHAPE" )
    WHERE ID = old.ID;
  END;
  CREATE TRIGGER GEBOUWGEOMETRIEN_UPDATE_GEOM AFTER UPDATE OF "SHAPE" ON GEBOUWGEOMETRIEN
  BEGIN
    UPDATE GEBOUWGEOMETRIEN 
    SET "GEBOUWGEOMETRIE" = AsGml( "SHAPE" )
    WHERE ID = old.ID;
 END;

COMMIT;