
SELECT  RRADRESSEN."ID", "RRHUISNUMMER", "RRINDEX", "SUBKANTONCODE", "RRSTRAATCODE", 
"ADRESID", HUISNUMMER
FROM "RRADRESSEN"

LEFT JOIN "ADRES_RRADRES_RELATIES"
	ON   "ADRES_RRADRES_RELATIES".RRADRESID = "RRADRESSEN".ID 

JOIN "HUISNUMMERS"
	ON   "ADRES_RRADRES_RELATIES".ADRESID = "HUISNUMMERS".ID  


WHERE HUISNUMMER NOT LIKE RRHUISNUMMER