SELECT "STRAATCODE" AS CRABCODE, "STRAATNAAM", 
WEGOBJECTEN.MORFOLOGISCHEWEGKLASSE AS MORFOLOGISCHEWEGKLASSE ,
STRAATKANTEN.EERSTEHUISNUMMER as EERSTEHUISNUMMER ,
STRAATKANTEN.LAATSTEHUISNUMMER as LAATSTEHUISNUMMER ,
WEGOBJECTEN.ID AS WEGOBJECTID ,
WEGVERBINDINGGEOMETRIEN.SHAPE

FROM "STRAATNAMEN"

INNER JOIN STRAATKANTEN 
	 ON STRAATNAMEN.ID = STRAATKANTEN.STRAATNAAMID

INNER JOIN WEGOBJECTEN 
	ON STRAATKANTEN.WEGOBJECTID = WEGOBJECTEN.ID

INNER JOIN WEGVERBINDINGGEOMETRIEN 
	ON WEGVERBINDINGGEOMETRIEN.WEGOBJECTID = WEGOBJECTEN.ID
    ;
